config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'sessions#new', as: 'home'
  resource :session, only: %i[new create destroy]
  resources :users
  get 'palindroms/index', as: 'form'
  post 'palindroms/result', to: 'palindroms#result'
  get 'users/index', as: 'all'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/palindrom.rb
# frozen_string_literal: true

# good
class Palindrom
    include ActiveModel::Model
    include ActiveModel::Validations
    include PalindromsHelper
    
    attr_accessor :num
  
    validates :num, presence: { message: 'не может быть пустым' }
    validates_numericality_of :num, only_integer: true, greater_than_or_equal_to: 0
    
    def print_res
        number = num.to_i
        return if number.negative?

        @hash = result_hash(number)
      end
  end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
    has_secure_password
  
    validates :email, presence: true, uniqueness: true
    validates :login, presence: true, uniqueness: true
  end

app/controllers/application_controller.rb
# frozen_string_literal: true

# main controller
class ApplicationController < ActionController::Base
    private
  
    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
    end
  
    def user_signed_in?
      current_user.present?
    end
  
    def autorize
      return if user_signed_in?
  
      flash[:warning] = 'Вы не авторизованы'
      redirect_to home_path
    end
  
    def no_autorize
      return unless user_signed_in?
  
      flash[:warning] = 'Вы уже авторизованы'
      redirect_to form_path
    end
  
    helper_method :current_user, :user_signed_in?
  end   

app/controllers/palindroms_controller.rb
# frozen_string_literal: true

# Palindroms controller
class PalindromsController < ApplicationController
  include PalindromsHelper
  before_action :autorize, only: %i[result index]

  def index; end

  def result
    @number = form_params
    @palindrom = Palindrom.new(@number)
    if @palindrom.valid?
      @hash = @palindrom.print_res
    end
  end

  private

  def form_params
    params.permit(:num)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# session controller
class SessionsController < ApplicationController
  before_action :no_autorize, only: %i[new create]
  before_action :autorize, only: :destroy
  def new; end

  def create
    user = User.find_by email: params[:email]
    if user&.authenticate(params[:password]) # Для безопасности(Если юзер будет nil,
      # то к нему не применится метод и мы направимся в else)
      session[:user_id] = user.id
      flash[:success] = 'Успешный вход'
      redirect_to form_path
    else
      flash[:warning] = 'Неправильный email или пароль'
      redirect_to home_path
    end
  end

  def destroy
    session.delete :user_id
    flash[:success] = 'Успешный выход'
    redirect_to home_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# User controller
class UsersController < ApplicationController
include UsersHelper
  before_action :no_autorize, only: %i[new create]
  before_action :autorize, only: %i[edit update]
  before_action :set_user, only: %i[edit update destroy]

  def index; end

  def show
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(new_all)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Добро пожаловать, #{@user.login}!"
      redirect_to form_path
    else
      redirect_to new_user_path, notice: 'Пароли не совпадают или данные логин или пароль существуют'
    end
  end

  def update
      if current_user.update new_all
      flash[:success] = 'Профиль обновлен'
      redirect_to edit_user_path(current_user)
      else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def new_all
    params.require(:user).permit(:email, :login, :password, :password_confirmation)
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/palindroms_helper.rb
# frozen_string_literal: true

# palindtoms helper
module PalindromsHelper
    def result_hash(num)
        arr = (2..num).map do |elem|
          c = 0;
          (2..elem).each do |i|
            if (elem.to_i) % i == 0 then c+=1
            end
          end
          if c == 1 then elem.to_i
          end
        end.compact
        Hash[arr.zip arr.map { |el| 2**el -1}]
      end
  end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab12</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
        <span class="fs-4"><strong><span class='purple'>Lab12</span></strong></span>
      <div class='text-right'>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-3 mb-md-0">
            <% if user_signed_in? %>
            <strong><span class='purple'><%= current_user.login %></span></strong>
            <li><strong><%= link_to "Редактировать профиль", edit_user_path(current_user), class: 'nav-link px-2' %></strong></li>
            <li><strong><%= link_to "Выйти", session_path, data: {turbo_method: :delete}, class: 'nav-link px-2' %></strong></li>
            <% else %>
            <li><strong><%= link_to "Войти", home_path, class: 'nav-link px-2' %></strong></li>
            <li><strong><%= link_to "Зарегистрироваться", new_user_path, class: 'nav-link px-2' %></strong></li>
            <% end %>
            <li><strong><%= link_to "Задание", form_path, class: 'nav-link px-2' %></strong></li>
            <li><strong><%= link_to "Список пользователей", all_path, class: 'nav-link px-2' %></strong></li>
        </ul>
         </div>
      </a>
    </header>
  <body>
  <div class = "container">
    <% flash.each do |type, msg| %>
      <div class='alert alert-info'>
        <strong id='msg'><%= msg %></strong>
      </div>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/palindroms/_result_page.html.erb
<% if @palindrom.valid? %>
    <h3>Таблица с результатами</h3>
    Введенное диапазон: [0, <%= @number[:num] %>]
    <table class = "tab">
        <tr>
        <th>Позиция</th>
        <th>Число</th>
        <th>Число Мерсена</th>
        </tr>
        <%i = 1%>
        <% @hash.each do |res, sqr|%>
        <tr>
            <td><%= i %></td>
            <td><%= res %></td>
            <td><%= sqr %></td>
        </tr>
        <% i = i + 1%>
        <% end%>
    </table>
    Количество таких чисел
    <p id="counter"><%= @hash.size %></p>
<% else %>
    <ul>
    <% @palindrom.errors.each do |error| %>
      <p><div class='alert alert-info'><%= error.full_message %></div></p>
    <% end %>
  </ul>
<% end %>

app/views/palindroms/index.html.erb
<h3>Задание:</h3> Найти и вывести числа Мерсена
<h4>Форма</h4>
<%= form_with url: '/palindroms/result', method: :post do |form| %>
  <p><%= form.label :query, "Введите верхнюю границу диапазона [0,n]" %></p>
  <p><%= form.number_field :num, :class => 'form-control', id: 'num' %></p>
  <p><%= form.submit("Найти", id: 'find') %></p>
<% end %>
<div id='result-container'></div>

app/views/palindroms/result.turbo_stream.erb
<%= turbo_stream.update 'result-container', partial: 'result_page' %>

app/views/users/edit.html.erb
<h1>Редактирование профиля</h1>
<%= form_with model: current_user do |form| %>
  <p><%= form.label :email, "Обновите email" %></p>
  <p><%= form.email_field :email, placeholder: current_user.email, class: 'form-control' %></p>
  <p><%= form.label :login, "Обновите логин" %></p>
  <p><%= form.text_field :login, placeholder: current_user.login, class: 'form-control' %></p>
  <p><%= form.label :password, "Обновите пароль" %></p>
  <p><%= form.password_field :password, class: 'form-control' %></p>
  <p><%= form.submit "Обновить" %></p>
<% end %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h4>Регистрация</h4>
<%= form_with model: @user do |form| %>
  <p><%= form.label :email, "Введите email" %></p>
  <p><%= form.email_field :email, placeholder: 'E-mail', class: 'form-control', id: 'email' %></p>
  <p><%= form.label :login, "Введите логин" %></p>
  <p><%= form.text_field :login, placeholder: 'login', class: 'form-control', id: 'login' %></p>
  <p><%= form.label :password, "Введите пароль" %></p>
  <p><%= form.password_field :password, class: 'form-control', id: 'pass' %></p>
  <p><%= form.label :password_confirmation, "Повторите пароль" %></p>
  <p><%= form.password_field :password_confirmation, class: 'form-control', id: 'pass_conf' %></p>
  <p><%= form.submit("Зарегистрироваться", id: 'btn') %></p>
<% end %>

app/views/users/show.html.erb
<h3>Просмотр всех пользователей</h3>
<% k = 1 %>
<%@users.each do |user|%>
<h3><%= k %> Пользователь:</h3>
    <p>Email: <%= user.email %></p>
    <p>Логин: <%= user.login %></p>
    <% k += 1 %>
<% end %>